import type { Metadata } from 'next'
import { Geist } from 'next/font/google'
import Header from '@/components/Header'
import { ThemeProvider } from 'next-themes'
import '@/assets/styles/globals.css'

const geist = Geist({
  subsets: ['latin']
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: {
  children: React.ReactNode
}) {
  return (
    <html lang='en' suppressHydrationWarning>
      <body className={`${geist.className} antialiased`}>
        <ThemeProvider attribute='class'>
          <div className='flex min-h-screen flex-col bg-white dark:bg-[#1C1C1C]'>
            <Header />
            <main className='flex-1 pt-5 pb-8 flex'>{children}</main>
          </div>
        </ThemeProvider>
      </body>
    </html>
  )
}
